title:            muanchiou
description:      who is muanchiou
url:              https://sansuiz.github.io/
permalink:        pretty
timezone:         America/New_York
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
